////
Proposito
-------
In a couple of sentences, briefly and at a high level describe the initiative
that RHC is supporting including business need, the technical challenge and the
approach to meeting the challenge.

Ejemplo
------
Red Hat Consulting was engaged by Acme Inc. to assist with the Application
Standardization 2.0 Project which seeks to address the audit risk associated
with non-compliant applications by automating the scanning, remediation and
reporting of non-compliant apps in the environment.  Ansible automation will be
used to establish standardized compliance scanning and remediation activities,
and record the results in the ServiceNow CMDB.

Ejemplo 2
------
(Prior to running the init script to build your engagement report, you can use
the following format to create a starter sentence using variables.  Note the
portions in "<>" are text meant to be replaced.)

Red Hat Consulting was engaged by {cust} to assist with {description} which
seeks to <describe what the initiative is meant to achieve> by <describe how
this engagement is going to support the initiative>.
////

{cust} contrató los servicios de Red Hat Consulting para que lo asista con {description} con la intención de (#TODO# describir qué se pretende lograr con esta iniciativa) a través de (#TODO# describir de qué modo este proyecto apoyará esa iniciativa).
